import {
  STEP_COMPRESSION,
  SYSTEM_COMPRESSION,
  VOICE_COMPRESSION,
  SEMANTIC_COMPRESSION,
  EXPORT_COMPRESSION,
} from "./wells.config";

export default {
  steps: STEP_COMPRESSION.steps, // ⬅ ВАЖНО
  system: SYSTEM_COMPRESSION,
  voice: VOICE_COMPRESSION,
  semantic: SEMANTIC_COMPRESSION,
  export: EXPORT_COMPRESSION,
};
