export const EDIT_FIELDS = [
  { key: "leak_id", label: "Индивидуальный номер утечки" },
  { key: "video_id", label: "Видео" },
  { key: "leak_speed", label: "Скорость утечки" },
  { key: "temperature", label: "Температура" },
  { key: "pressure", label: "Давление" },
  { key: "field", label: "УМГ" },
  { key: "station", label: "Компрессорная станция" },
  { key: "location", label: "Локация" },
  { key: "object", label: "Объект" },
  { key: "component", label: "Компонент" },
  { key: "leak_description", label: "Описание утечки", multiline: true },
  { key: "leak_cause", label: "Причина утечки", multiline: true },
  { key: "technological_solution", label: "Технологическое решение", multiline: true },
  { key: "repair_recommendation", label: "Решение / План устранения", multiline: true },
  { key: "materials_equipment", label: "МТР ремонта", multiline: true },
  { key: "note", label: "Примечание", multiline: true },
];

export const VIEW_FIELDS = [
  { key: "date", label: "Дата" },
  { key: "field", label: "УМГ" },
  { key: "station", label: "Компрессорная станция" },
  { key: "location", label: "Локация" },
  { key: "object", label: "Объект" },
  { key: "component", label: "Компонент" },
  { key: "leak_id", label: "Бирка" },
  { key: "video_id", label: "Видео" },
  { key: "leak_description", label: "Описание утечки", multiline: true },
  { key: "leak_cause", label: "Причина утечки", multiline: true },
  { key: "technological_solution", label: "Технологическое решение", multiline: true },
  { key: "repair_recommendation", label: "Решение / План устранения", multiline: true },
  { key: "materials_equipment", label: "Материалы и оборудование", multiline: true },
  { key: "note", label: "Примечание", multiline: true },
  { key: "leak_speed", label: "Скорость утечки" },
  { key: "pressure", label: "Давление" },
  { key: "temperature", label: "Температура" },
];
