export const headers = [
  "№",
  "Дата обнаружения",
  "Район",
  "Населенный пункт",
  "Адрес",
  "Объект",
  "Категория",
  "Индивидуальный номер утечки",
  "Компонент",
  "Номер видео",
  "Давление, атм",
  "Температура, °C",
  "Температура, К",
  "Оборудование для замера объёма утечки",
  "Серийный номер оборудования",
  "Погрешность",
  "Измеренная скорость утечки, л/мин",
  "Описание утечки",
  "Технологическое решение",
  "МТР ремонта (предполагаемый)",
  "Примечание",
  "Тип привода",
  "Тип присоединения",
  "Тип установки",
  "Координата X",
  "Координата Y",
  "Фото утечки",
];
export const keysOrder = [
  "index",
  "date",
  "subdivision",
  "deposit",
  "location",
  "object",
  "category",
  "leak_id",
  "component",
  "video_id",
  "pressure",
  "temperature",
  "temperature_K",
  "equipmentType",
  "serial_number",
  "uncertainty",
  "leak_speed",
  "leak_description",
  "technological_solution",
  "materials_equipment",
  "note",
  "actuator_type",
  "connection_type",
  "installation_type",
  "lat",
  "lng",
  "photo",
];
