export const headers = [
  "№",
  "Дата обнаружения",
  "УМГ",
  "Компрессорная станция",
  "Локация",
  "Объект",
  "Компонент",
  "Индивидуальный номер утечки",
  "Номер видео",
  "Описание утечки",
  "Причина утечки",
  "Технологическое решение",
  "Решение / План устранения",
  "МТР ремонта (предполагаемый)",
  "Примечание",
  "Измеренная скорость утечки, л/мин",
  "Измеренная скорость утечки, кг/ч",
  "Давление, атм",
  "Температура, °C",
  "Температура, К",
  "Процент газа на сжигание",
  "Процент газа на использование",
  "Общие годовые потери метана CH₄, м³/год",
  "Годовые потери метана CH₄, т/год",
  "Выбросы, CO₂-экв, т/год",
  "Выбросы, кг CO₂, т/год",
  "Потенциал глобального потепления ",
  "Тип привода",
  "Тип присоединения",
  "Тип установки",
  "Координата X",
  "Координата Y",
  "Фото утечки",
];
export const keysOrder = [
  "index",
  "date",
  "field",
  "station",
  "location",
  "object",
  "component",
  "leak_id",
  "video_id",
  "leak_description",
  "leak_cause",
  "technological_solution",
  "repair_recommendation",
  "materials_equipment",
  "note",
  "leak_speed",
  "leak_speed_kg",
  "pressure",
  "temperature",
  "temperature_K",
  "flareShare",
  "utilShare",
  "Total_Annual_Methane_Loss_m3_y",
  "Total_Annual_Methane_Loss_t_y",
  "Emissions_t_CO2eq_year",
  "Emissions_kg_CO2_eq_year",
  "GWP",
  "actuator_type",
  "connection_type",
  "installation_type",
  "lat",
  "lng",
  "photo",
];
