/**
 * Словари заголовков: как подписаны колонки в книгах, которые приходят на
 * импорт, и в какое поле записи каждая из них ложится.
 *
 * Отдельным модулем от `workbookSchema`, который эти словари применяет: там
 * логика поиска листа и шапки, здесь — данные, и растут они независимо.
 */

export const TECHNICAL_KEYS = [
  "index",
  "id",
  "created_at",
  "createdAt",
  "updatedAt",
  "date",
  "time",
  "status",
  "leak_id",
  "video_id",
  "detectedBy",
  "subdivision",
  "deposit",
  "field",
  "station",
  "district",
  "locality",
  "address",
  "location",
  "object",
  "category",
  "component",
  "pressure",
  "temperature",
  "temperature_K",
  "equipmentType",
  "serial_number",
  "uncertainty",
  "gasPercentage",
  "leak_speed",
  "leak_speed_kg_m",
  "leak_speed_kg_h",
  "flareShare",
  "utilShare",
  "Operating_mode",
  "weightedGWP",
  "Total_Annual_Methane_Loss_m3_y",
  "Total_Annual_Methane_Loss_kg_y",
  "Total_Annual_Methane_Loss_t_y",
  "Emissions_t_CO2eq_year",
  "Emissions_kg_CO2_eq_year",
  "GWP",
  "GWP_Minus",
  "gasType",
  "actuator_type",
  "connection_type",
  "installation_type",
  "lat",
  "lng",
  "leak_description",
  "leak_cause",
  "technological_solution",
  "repair_recommendation",
  "materials_equipment",
  "note",
  "photo",
  "photo_repair",
  "photo_after",
  "repairAt",
  "resolvedAt",
];

export const HEADER_ALIASES = {
  index: ["№", "номер", "n", "no"],
  date: ["дата", "дата обнаружения", "date", "detected date"],
  time: ["время", "время обнаружения", "time", "detected time"],
  leak_id: [
    "id утечки",
    "ид утечки",
    "номер утечки",
    "индивидуальный номер утечки",
    "индивидуальный номер бирки",
    "individual leak number",
    /*
     * «Номер бирки» и «№ бирки» — то, как эту колонку подписывают в файлах,
     * сделанных руками: приложение пишет «Индивидуальный номер утечки», а
     * человек за таблицей — как говорит. Заголовок нормализуется до «номер
     * бирки» и «бирки» соответственно, поэтому здесь нужны оба.
     */
    "номер бирки",
    "бирки",
    "бирка",
    "тег",
    "tag",
    "tag number",
    "tag no",
    "leak id",
    "leak_id",
  ],
  video_id: ["id видео", "video id", "video_id"],
  status: ["статус", "status", "состояние"],
  detectedBy: ["кто зафиксировал", "проверил", "detected by", "inspector"],
  subdivision: ["подразделение", "цех", "subdivision"],
  deposit: ["месторождение", "deposit"],
  field: ["участок", "field", "умг"],
  station: ["станция", "station", "кс"],
  district: ["район", "district"],
  locality: ["населенный пункт", "населённый пункт", "locality"],
  address: ["адрес", "address"],
  location: ["локация", "место", "location"],
  object: ["объект", "object"],
  category: ["категория", "category"],
  component: ["компонент", "component"],
  pressure: ["давление", "pressure"],
  temperature: ["температура", "temperature"],
  temperature_K: ["температура k", "temperature k", "temperature_k"],
  equipmentType: [
    "оборудование",
    "тип оборудования",
    "equipment",
    "equipment type",
  ],
  serial_number: ["серийный номер", "serial number", "serial_number"],
  uncertainty: ["погрешность", "uncertainty"],
  gasPercentage: [
    "содержание газа в смеси",
    "содержание газа",
    "gas content",
    "gas percentage",
    "gasPercentage",
  ],
  leak_speed: [
    "скорость утечки",
    "объем утечки",
    "объём утечки",
    "расход",
    "leak speed",
    "leak_speed",
  ],
  leak_speed_kg_m: ["кг/мин", "kg/min", "leak_speed_kg_m"],
  leak_speed_kg_h: ["кг/ч", "kg/h", "leak_speed_kg_h"],
  lat: ["широта", "latitude", "lat"],
  lng: ["долгота", "longitude", "lng", "lon"],
  leak_description: ["описание", "описание утечки", "description"],
  leak_cause: ["причина", "причина утечки", "cause"],
  technological_solution: ["техническое решение", "technological solution"],
  repair_recommendation: ["рекомендация", "repair recommendation"],
  materials_equipment: ["мтр и работы", "материалы", "materials"],
  note: ["комментарий", "примечание", "note", "comment"],
  photo: ["фото", "фото до", "photo"],
  photo_repair: ["фото в ремонте", "repair photo", "photo_repair"],
  repairAt: ["дата ремонта", "repair date", "repairAt"],
  repairTime: ["время ремонта", "repair time", "repairTime"],
  photo_after: ["фото после", "after photo", "photo_after"],
  resolvedAt: ["дата устранения", "resolved date", "resolvedAt"],
  resolvedTime: ["время устранения", "resolved time", "resolvedTime"],
};

export const MONITORING_HEADER_ALIASES = {
  index: ["№", "no", "n"],
  leak_id: ["бирка", "tag", "leak id", "leak_id", "id утечки"],
  roundNumber: ["обход", "round", "round number"],
  date: ["дата мониторинга", "monitoring date", "date"],
  time: ["время мониторинга", "monitoring time", "время", "time"],
  monitoredBy: ["кто мониторил", "monitored by", "inspector"],
  result: [
    "результат",
    "result",
    "утечка есть",
    "утечка есть?",
    "leak present",
    "is there a leak?",
  ],
  materials_equipment: ["мтр", "materials", "материалы"],
  comment: ["комментарий", "comment"],
  photo: ["фото мониторинга", "monitoring photo", "photo"],
  previousPhoto: [
    "предыдущее фото",
    "фото до обхода",
    "previous photo",
    "photo before round",
    "previousPhoto",
  ],
};

export const HISTORY_HEADER_ALIASES = {
  leak_id: ["бирка", "tag", "leak id", "leak_id", "id утечки"],
  date: ["дата", "date"],
  time: ["время", "time"],
  action: ["действие", "action"],
  user: ["пользователь", "user", "кто", "who"],
  text: ["текст", "text", "комментарий", "comment"],
  to: ["статус", "to", "status"],
  changes: ["изменения json", "changes json", "changes", "изменения"],
};
